# 02 Fibonacci test

Write a function fibonacci(n) that accepts a parameter `n` and returns the nth element of the Fibonacci sequence, recursively.

It must raise a `ValueError` exception with the message `"Invalid number"` if the given number is negative.

Use the provided `TestCase` to assert that your function works as expected.

Given that recursive functions can have high processing times, use memoization techniques to optimize the execution of your function and pass the third test successfully.


## Instructions

1. Run the tests with `python -m unittest discover`
2. Commit your work when the command above reports an OK result
